/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutMovie: typeof import('./components/Movie/AboutMovie.vue')['default']
    ActivityChat: typeof import('./components/Chat/ActivityChat.vue')['default']
    AppHeader: typeof import('./components/Header/AppHeader.vue')['default']
    RandomMovie: typeof import('./components/Movie/RandomMovie.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
